interfaces = []
exclude = [
    "**/*__pycache__",
    "**/*egg-info",
    "**/docs",
    "**/tests",
    "**/venv",
]
source_roots = [
    ".",
]

[[modules ]]
path = "notebooks"
depends_on = []

[[modules ]]
path = "model.fno"
depends_on = []

[[modules ]]
path = "logs"
depends_on = []

[[modules ]]
path = "utils"
depends_on = []

[[modules ]]
path = "model"
depends_on = []

[[modules ]]
path = "report"
depends_on = []

[[modules ]]
path = "model.deeponet"
depends_on = []

[[modules ]]
path = "data"
depends_on = []

[[modules ]]
path = "tests"
depends_on = []
